title: Link2Cyber
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
search_enabled: true
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

nav_sort: case_insensitive

aux_links:
  "Back to GitHub":
    - "https://github.com/benlinkous/link2cyber-website"

callouts:
  note:
    title: Note
    color: blue
